### ISSUE TITLE
TypeError: Cannot read property 'modifier' of undefined

### ISSUE THREAD

**Issue by muety** [sinclairzx81/typebox#127]
```
$ ts-node-dev src/app.ts
[INFO] 17:11:35 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.2)
TypeError: Cannot read property 'modifier' of undefined
    at /home/me/dev/myapp/node_modules/@sinclair/typebox/typebox.js:111:31
    at Array.filter (<anonymous>)
    at TypeBuilder.Object (/home/me/dev/myapp/node_modules/@sinclair/typebox/typebox.js:109:41)
    at Object.<anonymous> (/home/me/dev/myapp/packages/shared/src/types/recipe.ts:44:32)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module._compile (/home/me/dev/myapp/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.nodeDevHook [as .js] (/home/me/dev/myapp/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
[ERROR] 17:11:40 TypeError: Cannot read property 'modifier' of undefined
```

**Comment by sinclairzx81** [comment]
@muety Can you provide a bit more information? If you can submit a repro ill be able to take a closer look at the issue.

**Comment by sinclairzx81** [comment]
Going to close this off as there is not enough information in that stack trace to identify the problem. I'm guessing that there has been an attempt to `Partial`, `Required`, `Pick` or `Omit` on a referenced type (which would cause this error). There has been a enhancement on `0.23.0` that implements references for these object modifiers.

Help that helps
S

**Comment by muety** [comment]
Used typebox version is 0.22.1 and the issue occurs, among others, when using `Static` modifiers.

```typescript
export type UserType = Static<typeof User>

export const User = Type.Object({
  id: Type.Number(),
  firstName: Type.String(),
  lastName: Type.String(),
  email: Type.String()
})
```

**Comment by sinclairzx81** [comment]
@muety That code doesn't look like it would cause a problem. Are you using `Type.Strict()` on any of these schemas?
