### ISSUE TITLE
Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by simon-tannai** [sinclairzx81/typebox#136]
Hello 👋

I'm using Typebox to define Fastify's schema. But I got an error on runtime: 
```text
/usr/src/app/dist/types/rest/registration.rest.type.js:8
    email: user_db_type_1.userDbSchema.properties.email,
                                       ^

TypeError: Cannot read property 'properties' of undefined
    at Object.<anonymous> (/usr/src/app/dist/types/rest/registration.rest.type.js:8:40)
```

registration.rest.type:
```typescript
export const registrationRestSchema = Type.Strict(Type.Object({
  email: userDbSchema.properties.email,
  firstName: userDbSchema.properties.firstName,
  lastName: userDbSchema.properties.lastName,
  phoneNumber: userDbSchema.properties.phoneNumber,
  password: Type.RegEx(strongPasswordRegexp, {
    example: 'a_Str0ng_Passw0rd',
    description: 'Strong password choose by the user',
  }),
  confirmedPassword: Type.RegEx(strongPasswordRegexp, {
    example: 'a_Str0ng_Passw0rd',
    description: 'Exactly the same value than password field',
  }),
  invitationCode: Type.Optional(Type.String()),
}));
```

The userDbSchema: 
```typescript
export const userDbSchema = Type.Strict(Type.Object({
  ...defaultDbSchema.properties,
  email: Type.RegEx(emailAddressRegexp, {
    example: 'john.doe@gmail.com',
    description: 'Email of the user',
    minLength: 3,
    maxLength: 320,
  }),
  firstName: Type.String({
    example: 'John',
    description: 'First name of the user',
    minLength: 1,
    maxLength: 500,
  }),
  [...]
}));
```

I also tried without using `Type.Strict()` but it changed nothing.

Is there another way to refer to a property from another Typebox object ?

**Comment by sinclairzx81** [comment]
@simon-tannai Hi,

### Type.Strict()

When using Fastify, the recommendation is not to use `Type.Strict()`, but rather configure the Fastify's AJV validator to support the `kind` and `modifier` keywords. This configuration will be a requirement from Fastify version 4 onwards, but shouldn't be an issue for Fastify 3.x. The `Type.Strict()` function is used specifically to remove the `kind` and `modifier` properties from the underlying schemas only.

### Sharing Properties

If you need to share common properties, it is a good idea to remove these properties from the object and into their own types. For example...

```typescript
// Shared Common Properties
export const Email = Type.String({ format: 'email' })
export const UserId = Type.String({ format: 'uuid' })
export const FirstName = Type.String({ minLength: 1, maxLength: 1000 })
export const LastName = Type.String({ minLength: 1, maxLength: 1000 })

// UserDbSchema
export const UserDbSchema = Type.Object({
    userId: UserId,
    firstName: FirstName,
    lastName: LastName,
    email: Email,
    // ... etc
})
// Registration Schema
export const RegistrationRestSchema = Type.Object({
    userId: UserId,
    firstName: FirstName,
    lastName: LastName,
    email: Email,
    // ...etc
})
```
### Cannot read property 'properties' of undefined

It's difficult to know what the issue is here, but I would recommend `console.log(schema)` on the Schema to see if the properties exists.

```typescript
const T = Type.Object({
   a: Type.Number(),
   b: Type.String(),
   c: Type.Boolean()
})

console.log(T)
// prints: {
//    type: 'object',
//    properties: {
//      a: { type: 'number' },
//      b: { type: 'string' },
//      c: { type: 'boolean' },
//    },
//    required: ['a', 'b', 'c']
// }
```

Hope that helps
S

**Comment by simon-tannai** [comment]
Hello @sinclairzx81 

I have follow your advices:

_user.type.ts_:
```typescript
export const userEmailSchema = Type.RegEx(emailAddressRegexp, {
  example: 'john.doe@gmail.com',
  description: 'Email of the user',
  minLength: 3,
  maxLength: 320,
});

export const userFirstNameSchema = Type.String({
  example: 'John',
  description: 'First name of the user',
  minLength: 1,
  maxLength: 500,
});

export const userLastNameSchema = Type.String({
  example: 'Doe',
  description: 'Last name of the user',
  minLength: 1,
  maxLength: 500,
});

export const userPhoneNumberSchema = Type.RegEx(frenchPhoneNumberRegexp, {
  example: '0701020304',
  description: 'Phone number of the user',
  minLength: 0,
  maxLength: 20,
});

export const userDbSchema = Type.Object({
  ...defaultDbSchema.properties,
  email: userEmailSchema,
  firstName: userFirstNameSchema,
  lastName: userLastNameSchema,
  phoneNumber: userPhoneNumberSchema,
  hash: Type.String({
    example: 'abc123.',
    description: 'Hash password',
    minLength: 60,
    maxLength: 60,
  }),
  [ ... ]
});
```

_registration-rest.type.ts_:
```typescript
export const registrationRestSchema = Type.Object({
  email: userEmailSchema,
  firstName: userFirstNameSchema,
  lastName: userLastNameSchema,
  phoneNumber: userPhoneNumberSchema,
  password: Type.RegEx(strongPasswordRegexp, {
    example: 'a_Str0ng_Passw0rd',
    description: 'Strong password choose by the user',
  }),
 [ ... ]
});
```

I no longer have the previous error, but I got another one:
```bash
/usr/src/app/node_modules/@sinclair/typebox/typebox.js:114
            return (candidate.modifier &&
                              ^

TypeError: Cannot read property 'modifier' of undefined
    at /usr/src/app/node_modules/@sinclair/typebox/typebox.js:114:31
    at Array.filter (<anonymous>)
    at TypeBuilder.Object (/usr/src/app/node_modules/@sinclair/typebox/typebox.js:112:41)
    at Object.<anonymous> (/usr/src/app/dist/types/rest/registration-rest.type.js:7:49)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

Line 7 from registration-rest.type.js:
```javascript
exports.registrationRestSchema = typebox_1.Type.Object({
    email: user_db_type_1.userEmailSchema,
    firstName: user_db_type_1.userFirstNameSchema,
    lastName: user_db_type_1.userLastNameSchema,
    phoneNumber: user_db_type_1.userPhoneNumberSchema,
    password: typebox_1.Type.RegEx(regexp_1.strongPasswordRegexp, {
        example: 'a_Str0ng_Passw0rd',
        description: 'Strong password choose by the user',
    }),
    [ ... ]
});
```

As you explain [in this comment](https://github.com/sinclairzx81/typebox/issues/127#issuecomment-983375360), this error may throwned by `Type.Strict()`. I'm not using it here.

**Comment by sinclairzx81** [comment]
@simon-tannai Hi, just ran your code locally.

```typescript

const emailAddressRegexp = /regex-not-specified/
const strongPasswordRegexp = /regex-not-specified/
const frenchPhoneNumberRegexp = /regex-not-specified/

export const userEmailSchema = Type.RegEx(emailAddressRegexp, {
    example: 'john.doe@gmail.com',
    description: 'Email of the user',
    minLength: 3,
    maxLength: 320,
});

export const userFirstNameSchema = Type.String({
    example: 'John',
    description: 'First name of the user',
    minLength: 1,
    maxLength: 500,
});

export const userLastNameSchema = Type.String({
    example: 'Doe',
    description: 'Last name of the user',
    minLength: 1,
    maxLength: 500,
});

export const userPhoneNumberSchema = Type.RegEx(frenchPhoneNumberRegexp, {
    example: '0701020304',
    description: 'Phone number of the user',
    minLength: 0,
    maxLength: 20,
});

export const userDbSchema = Type.Object({
    // ...defaultDbSchema.properties,
    email: userEmailSchema,
    firstName: userFirstNameSchema,
    lastName: userLastNameSchema,
    phoneNumber: userPhoneNumberSchema,
    hash: Type.String({
        example: 'abc123.',
        description: 'Hash password',
        minLength: 60,
        maxLength: 60,
    }),
});

export const registrationRestSchema = Type.Object({
    email: userEmailSchema,
    firstName: userFirstNameSchema,
    lastName: userLastNameSchema,
    phoneNumber: userPhoneNumberSchema,
    password: Type.RegEx(strongPasswordRegexp, {
        example: 'a_Str0ng_Passw0rd',
        description: 'Strong password choose by the user',
    })
});

console.log(registrationRestSchema)
/*
prints: 
{
  kind: Symbol(ObjectKind),
  type: 'object',
  properties: {
    email: {
      example: 'john.doe@gmail.com',   
      description: 'Email of the user',
      minLength: 3,
      maxLength: 320,
      pattern: 'regex-not-specified',  
      kind: Symbol(StringKind),
      type: 'string'
    },
    firstName: {
      example: 'John',
      description: 'First name of the user',
      minLength: 1,
      maxLength: 500,
      kind: Symbol(StringKind),
      type: 'string'
    },
    lastName: {
      example: 'Doe',
      description: 'Last name of the user',
      minLength: 1,
      maxLength: 500,
      kind: Symbol(StringKind),
      type: 'string'
    },
    phoneNumber: {
      example: '0701020304',
      description: 'Phone number of the user',
      minLength: 0,
      maxLength: 20,
      pattern: 'regex-not-specified',
      kind: Symbol(StringKind),
      type: 'string'
    },
    password: {
      example: 'a_Str0ng_Passw0rd',
      description: 'Strong password choose by the user',
      pattern: 'regex-not-specified',
      kind: Symbol(StringKind),
      type: 'string'
    }
  },
  required: [ 'email', 'firstName', 'lastName', 'phoneNumber', 'password' ]
}
*/
```
This looks fine to me, however I don't know what `...defaultDbSchema.properties` is, or why it's being spread on the `userDbSchema` object type (I've commented this out in the example above as this schema hasn't been provided). I'm guessing that whatever the issue is, it's probably has to do with the `defaultDbSchema`.

Is the `defaultDbSchema` a TypeBox type? Does it use `Type.Strict()`?

**Comment by simon-tannai** [comment]
Hello @sinclairzx81  👋

I did a massive refactoring of my code and all is working fine now 🚀

The issue was that I made a kind of deep "link" between Typebox's objects by using the `properties` attribute, like this: 
```typescript
export const example1Schema = Type.Object({
    email: userEmailSchema,
    [...]
});

export const example2Schema = Type.Object({
    ...example1Schema.properties,
    password: Type.String(),
    [...]
});

export const example3Schema = Type.Object({
    ...example2Schema.properties,
    [...]
});
```

Now, I'm using `Type.Intersect()` to reuse an existing Typebox's object:
```typescript
export const example1Schema = Type.Object({
    email: userEmailSchema,
    [...]
});

export const example2Schema = Type.Intersect([
    example1Schema,
    Type.Object({
      password: Type.String(),
      [...]
    }),
]);
```

I have also defined each shared properties into their own object:
```typescript
export const userEmailSchema = Type.RegEx(emailAddressRegexp, {
  example: 'john.doe@gmail.com',
  description: 'Email of the user',
  minLength: 3,
  maxLength: 320,
});

export const userFirstNameSchema = Type.String({
  example: 'John',
  description: 'First name of the user',
  minLength: 1,
  maxLength: 500,
});

export const userDbSchema = Type.Intersect([
  defaultDbSchema,
  Type.Object({
    email: userEmailSchema,
    firstName: userFirstNameSchema,
    [...]
  }),
]);
```

With that two improvements, all is working fine ✌️

Many thanks @sinclairzx81 for your help and your advise 🥳
