### ISSUE TITLE
LiteralKind is not defined when using fast-json-stringify

### ISSUE THREAD

**Issue by mmatloch** [sinclairzx81/typebox#44]
Type.Literal with Type.Union causes a ReferenceError error when using fast-json-stringify.

```typescript
Type.Object({
  option: Type.Union([Type.Literal('pizza'), Type.Literal('salad'), Type.Literal('pie')]),
});
```

```
ReferenceError: LiteralKind is not defined
	at Object.$main (eval at build (/usr/src/app/.yarn/cache/fast-json-stringify-npm-2.2.9-c510e40cf5-f481a8e3e1.zip/node_modules/fast-json-stringify/index.js:158:20), <anonymous>:181:44)
	at serialize (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/validation.js:116:41)
	at preserializeHookEnd (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/reply.js:348:15)
	at next (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/hooks.js:198:7)
	at Object.<anonymous> (/usr/src/app/packages/tsi-core/src/plugins/replyCommonHeadersPlugin.ts:30:20)
	at next (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/hooks.js:202:34)
	at Object.<anonymous> (/usr/src/app/packages/tsi-core/src/plugins/replyResourcePlugin.ts:30:9)
	at next (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/hooks.js:202:34)
	at onSendHookRunner (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/hooks.js:216:3)
	at preserializeHook (/usr/src/app/.yarn/cache/fastify-npm-3.7.0-a75b1a843e-1a1d0d55eb.zip/node_modules/fastify/lib/reply.js:327:5)
```

Typebox version: **0.12.4**

**Comment by sinclairzx81** [comment]
@mmatloch Hi, I'm able to reproduce the issue. But but it looks like an issue with `fast-json-stringify`. I've reproduced this error without using TypeBox at all.  The issue seems to be related to how `fast-json-validate` deals with `anyOf` schemas. As below.

### Working

The following code works fine.

```typescript
import * as fastJson from 'fast-json-stringify'

const working= fastJson({
  type: "object",
  properties: {
    value: {
      anyOf: [
        { type: "string", enum: [ "foo" ] },
        { type: "string", enum: [ "bar" ] },
        { type: "string", enum: [ "baz" ] }
      ]
    }
  },
  required: [ "value" ]
})

console.log(working({ value: 'foo' }))
```
### Not Working
The following code throws an error trying to resolve the `symbol LIteralKind`. Note that `ObjectKind` and `UnionKind` are fine, however `LiteralKind` is not, possibly related to how `anyOf` is handled in `fast-json-stringify`. 
```typescript
import * as fastJson from 'fast-json-stringify'

const ObjectKind  = Symbol('LiteralKind')
const UnionKind   = Symbol('UnionKind')
const LiteralKind = Symbol('LiteralKind')

const not_working = fastJson({
  kind: ObjectKind,
  type: "object",
  properties: {
    value: {
      kind: UnionKind,
      anyOf: [
        { kind: LiteralKind, type: "string", enum: [ "foo" ] }, // fail ?
        { kind: LiteralKind, type: "string", enum: [ "bar" ] }, // fail ?
        { kind: LiteralKind, type: "string", enum: [ "baz" ] }  // fail ?
      ]
    }
  },
  required: [ "value" ]
})

console.log(not_working({ value: 'foo' }))
```
Which results in the following AJV error originating from `fast-json-stringify`.
```bash
undefined:132
            if(ajv.validate({ kind: Symbol(LiteralKind), type: 'string', enum: [ 'foo' ] }, obj["value"]))
                                           ^

ReferenceError: LiteralKind is not defined
    at $main (eval at build (C:\Users\sinclair\Desktop\stringify\node_modules\fast-json-stringify\index.js:158:20), <anonymous>:132:44)
    at Object.<anonymous> (C:\Users\sinclair\Desktop\stringify\index.js:94:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
### AJV Test
To further narrow the problem. The following code runs the same validator against the same schema using Ajv directly. This code works as expected.
```typescript
import * as Ajv from 'ajv'

const ajv         = new Ajv()
const ObjectKind  = Symbol('LiteralKind')
const UnionKind   = Symbol('UnionKind')
const LiteralKind = Symbol('LiteralKind')

const result = ajv.validate({
  kind: ObjectKind,
  type: "object",
  properties: {
    value: {
      kind: UnionKind, 
      anyOf: [
        { kind: LiteralKind, type: "string", enum: [ "foo" ] },
        { kind: LiteralKind, type: "string", enum: [ "bar" ] },
        { kind: LiteralKind, type: "string", enum: [ "baz" ] }
      ]
    }
  },
  required: [ "value" ]
}, { 
  value: 'foo'
})

console.log('is valid:', result) // true
```
I'll open an issue on the `fast-json-stringify` project, but there isn't much I can do to resolve this in TypeBox. I'll leave the issue open for the time being.

Cheers mate
S

**Comment by sinclairzx81** [comment]
@mmatloch Will close off this issue as the fix should roll through on the next npm push for `fast-json-stringify`

Cheers mate
S
