### ISSUE TITLE
TypeCompiler compiling function schema causes error

### ISSUE THREAD

**Issue by stevezhu** [sinclairzx81/typebox#532]
TypeBox version: 0.31.0

The following code causes the error below.
```typescript
import { Type } from '@sinclair/typebox';
import { TypeCompiler } from '@sinclair/typebox/compiler';

export const checker = TypeCompiler.Compile(
  Type.Function(
    [Type.Number()],
    Type.Number(),
  )
);
```

Error:
```shell
/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:134
        const references_ = (0, guard_1.IsString)(schema.$id) ? [...references, schema] : references;
                                                         ^


TypeError: Cannot read properties of undefined (reading '$id')
    at Visit (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:134:58)
    at schema (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:94:126)
    at Array.some (<anonymous>)
    at TFunction (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:94:109)
    at Visit (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:151:24)
    at Object.Has (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/value/transform.js:202:16)
    at TypeCheck (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/compiler/compiler.js:47:54)
    at Object.Compile (/home/runner/TypeBox-Error/node_modules/@sinclair/typebox/compiler/compiler.js:633:16)
    at <anonymous> (/home/runner/TypeBox-Error/index.ts:4:37)
    at Object.<anonymous> (/home/runner/TypeBox-Error/index.ts:9:1)

Node.js v18.12.1
exit status 1
```

**Comment by sinclairzx81** [comment]
@stevezhu Hi, thanks for reporting.

Have published a fix for this on `0.31.1`. The issue was to do with a preflight optimization check that gets run post compilation. The check tests if the type contains a transform codec (these were added on 0.31.0), however there was bug in both Function and Constructor checks that wasn't caught in the test suite. Have added these for these. This was a good catch!

Related PR can be found https://github.com/sinclairzx81/typebox/pull/533

Will close off this issue for now, thanks again for reporting!
Cheers
S
