### ISSUE TITLE
 Error TS2315  with TSDX

### ISSUE THREAD

**Issue by MonsignorEduardo** [sinclairzx81/typebox#76]
I'm using TSDX with defaults settings and getting a TS2315

```import { Static, Type } from '@sinclair/typebox';

export const phoneInputValue = Type.Object({
  countryCode: Type.String(),
  isoCode: Type.String(),
  phone: Type.String(),
});

export type PhoneInputValueType = Static<typeof phoneInputValue>;
```

The error is : 
```$ tsdx build
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
✓ Creating entry file 1 secs
(typescript) Error: /home/edy/projectos/temp/prueba/src/index.ts(9,35): semantic error TS2315: Type 'Static' is not generic.
Error: /home/edy/projectos/temp/prueba/src/index.ts(9,35): semantic error TS2315: Type 'Static' is not generic.
    at error (/home/edy/projectos/temp/prueba/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/home/edy/projectos/temp/prueba/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/home/edy/projectos/temp/prueba/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/home/edy/projectos/temp/prueba/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at /home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (/home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (/home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (/home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (/home/edy/projectos/temp/prueba/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17)
```

**Comment by sinclairzx81** [comment]
@MonsignorEduardo Hi, TypeBox has a minimum requirement on TypeScript `4.0.1` and it looks like TSDX is currently pulling TypeScript `3.7.3` https://github.com/formium/tsdx/blob/master/package.json#L99.

Unfortunately, there isn't much I can do to resolve this issue as TypeBox relies heavily on TypeScript `4.x` functionality. There's a couple of things you can try however.

- You can try convince the TSDX team to upgrade TypeScript to at least `4.x`.
- You can try source an older version of TypeBox. `@sinclair/typebox@0.8.1` I think sources `typescript@3.8.3`
- You can try either of these (both of which are mine). These should let you bundle modern TS code with minimal configuration.
   - TypeScript Bundle - https://github.com/sinclairzx81/typescript-bundle
   - Hammer - https://github.com/sinclairzx81/hammer
   
Hope that helps!
S

**Comment by MonsignorEduardo** [comment]
Got it currently I'm using the yarn with resolutions to fix it. 
```
"resolutions": {
    "**/typescript": "^4.3.2"
  }
```
